# Generated by Django 4.2.1 on 2024-01-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
