# Generated by Django 4.2.1 on 2024-01-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_bookings_booking_rename_rooms_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
