# Generated by Django 4.2.1 on 2024-01-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number_of_beds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='snacks',
            field=models.BooleanField(default=False),
        ),
    ]
