# Generated by Django 4.2.1 on 2024-01-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booking_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='booking_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_restrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_wardrobes',
            field=models.IntegerField(default=1),
        ),
    ]
