# Generated by Django 4.2.1 on 2024-01-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_room_booking_end_date_room_booking_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.URLField(),
        ),
    ]
