# Generated by Django 4.2.1 on 2024-01-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ending_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='starting_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.CharField(max_length=2000),
        ),
    ]
